### ISSUE TITLE
crisprai

### ISSUE THREAD

**Issue by Jfortin1** [Jfortin1/crisprScore#2]
Create following folders to add example data: 
- `inst/crisprai/test_data_crispra`
- `inst/crisprai/test_data_crispri`

Need additional arguments:
- chromatinFiles=c(dnase=, rnase=, mnase)
- genomeFastFile (string)
- trainedModelFiles (crispra=, crispri=)

**Comment by developerpiru** [comment]
Example CRISPRa files added to `inst/crisprai/test_data_crispra`:

- `crispra_sgrna_example.txt`
- `crispra_tss_example.txt`

Example CRISPRi files added to `inst/crisprai/test_data_crispri`:

- `crispri_sgrna_example.txt`
- `crispri_tss_example.txt`

Additional arguments added to pass large files.
