### ISSUE TITLE
New Feature Request: Elevation Off-target Score and CRIPSRoff Score

### ISSUE THREAD

**Issue by mzhibo** [Jfortin1/crisprScore#5]
Hi,
I have been using your new CRISPR Design tools recently and found it to be very helpful in CRISPR gRNA design. While I was searching for the best performing off-target prediction algorithms, I found those two more recent method: Microsoft ML-based Elevation score (sister algorithm of the Azimuth on-target prediction), and the gRNA binding free energy based ML algorithm-CRISPRoff. 
Both showed superior performance than the MIT score and CDF scores, especially the CRIPSRoff Score.
I wonder if you could integrate those two methods in your off-target prediction methods collection. Below are the links:
https://github.com/microsoft/Elevation
https://github.com/RTH-tools/crisproff
Thank you for considering.
Best,
Zhibo

**Comment by Jfortin1** [comment]
Hi @mzhibo,

Thanks for the suggestions. The CRISPRoff should be relatively easy to implement, but Elevation is not given the complicated dependencies it has, and given its similar performance to CFD (and coming from the same authors), we will not prioritize it.

**Comment by mzhibo** [comment]
@Jfortin1 Thank you so much for considering including CRISPRoff!

**Comment by Jfortin1** [comment]
Move to https://github.com/crisprVerse/crisprScore/issues/3
